package vodafone.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Feb 21 12:41:20 UTC 2021]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TurbineGroupPeer
    extends vodafone.om.BaseTurbineGroupPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1613911280867L;

}
